# Generated by Django 2.1.7 on 2019-04-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('attending', models.BooleanField()),
                ('meal_selection', models.CharField(choices=[('V', 'Vegetarian'), ('B', 'Beef'), ('C', 'Chicken')], max_length=1)),
            ],
        ),
    ]
